version: '3'
services:
  reader:
    build:
      context: .
      dockerfile: images/node-reader/Dockerfile
    user: "root"
    working_dir: /workspace/apps/server
    environment:
      - NODE_ENV=production
    volumes:
      - .:/workspace
      - root_node_modules:/workspace/node_modules
      - server_node_modules:/workspace/apps/server/node_modules
      - web_node_modules:/workspace/apps/web/node_modules
      - api_contracts_node_modules:/workspace/packages/api-contracts/node_modules
    command: "pnpm --filter @waxonedge/server start_deamon_bigmem deamon=reader"
#    command: "pnpm --filter @waxonedge/server start_deamon_inspect deamon=reader"
#    ports:
#      - "9229:9229"
    depends_on:
      - redis
  readerrows:
    build:
      context: .
      dockerfile: images/node-reader/Dockerfile
    user: "root"
    working_dir: /workspace/apps/server
    environment:
      - NODE_ENV=production
    volumes:
      - .:/workspace
      - root_node_modules:/workspace/node_modules
      - server_node_modules:/workspace/apps/server/node_modules
      - web_node_modules:/workspace/apps/web/node_modules
      - api_contracts_node_modules:/workspace/packages/api-contracts/node_modules
    command: "pnpm --filter @waxonedge/server start_deamon_bigmem deamon=reader_rows"
    depends_on:
      - redis
  indexer:
    build:
      context: .
      dockerfile: images/node-reader/Dockerfile
    user: "root"
    working_dir: /workspace/apps/server
    environment:
      - NODE_ENV=production
    volumes:
      - .:/workspace
      - root_node_modules:/workspace/node_modules
      - server_node_modules:/workspace/apps/server/node_modules
      - web_node_modules:/workspace/apps/web/node_modules
      - api_contracts_node_modules:/workspace/packages/api-contracts/node_modules
    ports:
      - "8200"
    command: "pnpm --filter @waxonedge/server start_deamon_bigmem deamon=indexer"
    depends_on:
      - redis
  liquiditypricesindexer:
    build:
      context: .
      dockerfile: images/node-reader/Dockerfile
    user: "root"
    working_dir: /workspace/apps/server
    environment:
      - NODE_ENV=production
    volumes:
      - .:/workspace
      - root_node_modules:/workspace/node_modules
      - server_node_modules:/workspace/apps/server/node_modules
      - web_node_modules:/workspace/apps/web/node_modules
      - api_contracts_node_modules:/workspace/packages/api-contracts/node_modules
    command: "pnpm --filter @waxonedge/server start_deamon deamon=liquidity_prices_indexer"
    depends_on:
      - indexer
  laststatsindexer:
    build:
      context: .
      dockerfile: images/node-reader/Dockerfile
    user: "root"
    working_dir: /workspace/apps/server
    environment:
      - NODE_ENV=production
    volumes:
      - .:/workspace
      - root_node_modules:/workspace/node_modules
      - server_node_modules:/workspace/apps/server/node_modules
      - web_node_modules:/workspace/apps/web/node_modules
      - api_contracts_node_modules:/workspace/packages/api-contracts/node_modules
    ports:
      - "8220"
    command: "pnpm --filter @waxonedge/server start_deamon_bigmem deamon=last_stats_indexer"
    depends_on:
      - indexer
  klinesindexer:
    build:
      context: .
      dockerfile: images/node-reader/Dockerfile
    user: "root"
    working_dir: /workspace/apps/server
    stop_grace_period: 60s
    environment:
      - NODE_ENV=production
    volumes:
      - .:/workspace
      - root_node_modules:/workspace/node_modules
      - server_node_modules:/workspace/apps/server/node_modules
      - web_node_modules:/workspace/apps/web/node_modules
      - api_contracts_node_modules:/workspace/packages/api-contracts/node_modules
    ports:
      - "8210"
    command: "pnpm --filter @waxonedge/server start_deamon_bigmem deamon=klines_indexer"
    depends_on:
      - indexer
      - redis
  api:
    build:
      context: .
      dockerfile: images/node-reader/Dockerfile
    user: "root"
    working_dir: /workspace/apps/server
    environment:
      - NODE_ENV=production
    volumes:
      - .:/workspace
      - root_node_modules:/workspace/node_modules
      - server_node_modules:/workspace/apps/server/node_modules
      - web_node_modules:/workspace/apps/web/node_modules
      - api_contracts_node_modules:/workspace/packages/api-contracts/node_modules
    command: "pnpm --filter @waxonedge/server start_api"
    ports:
      - 8000:8000
    depends_on:
      - indexer
      - redis
    restart: on-failure
  socketio:
    build:
      context: .
      dockerfile: images/node-reader/Dockerfile
    user: "root"
    working_dir: /workspace/apps/server
    environment:
      - NODE_ENV=production
    volumes:
      - .:/workspace
      - root_node_modules:/workspace/node_modules
      - server_node_modules:/workspace/apps/server/node_modules
      - web_node_modules:/workspace/apps/web/node_modules
      - api_contracts_node_modules:/workspace/packages/api-contracts/node_modules
    ports:
      - 8010:8010
    command: "pnpm --filter @waxonedge/server start_deamon deamon=socketio_server"
    depends_on:
      - redis
  redis:
    image: 'redis:7'
    ports:
      - 6379:6379
    volumes:
      - ./services_conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
#  rabbitmq:
#    image: 'rabbitmq:3.11.13-management-alpine'
#    environment:
#      -  RABBITMQ_DEFAULT_USER=swaplog
#      -  RABBITMQ_DEFAULT_PASS=swaplog
volumes:
  root_node_modules:
  server_node_modules:
  web_node_modules:
  api_contracts_node_modules:
